#!/bin/bash
echo "=== ArduHumanoid SITL Launch ==="
echo "Open 3 terminals and run:"
echo ""
echo "Terminal 1:"
echo "  cd ~/ardupilot && Tools/autotest/sim_vehicle.py -v ArduCopter -f gazebo-iris --model JSON --console"
echo "  Then type: output add 127.0.0.1:14551"
echo ""
echo "Terminal 2:"
echo "  gz sim ~/humanoid-ardupilot-sitl/worlds/ardupilot_humanoid.sdf"
echo ""
echo "Terminal 3:"
echo "  python3 ~/humanoid-ardupilot-sitl/scripts/balance_controller.py"
